server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plan_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    trailing-slash:
      match: true
